name: Frontend Preview & E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "**"
      - ".github/workflows/frontend-preview-e2e.yml"

jobs:
  preview-and-e2e:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (prebuilt deploy 用)
        run: npm run build

      - name: Add Vercel CLI
        run: npm i -D vercel

      # ← ここがポイント：IDではなく「プロジェクト名 + 組織スラッグ」でリンク
      - name: Link Vercel Project (non-interactive)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel link \
            --project "${{ secrets.VERCEL_PROJECT_NAME }}" \
            --yes \
            --token "$VERCEL_TOKEN" \
            --scope "${{ secrets.VERCEL_ORG_SLUG }}"

      - name: Deploy to Vercel (Preview)
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # preview 環境のenvも取得（.vercel/project.json が生成済みならOK）
          npx vercel pull --yes --environment=preview --token "$VERCEL_TOKEN" --scope "${{ secrets.VERCEL_ORG_SLUG }}"
          # dist をそのままアップ
          URL=$(npx vercel deploy --prebuilt --yes --token "$VERCEL_TOKEN" --scope "${{ secrets.VERCEL_ORG_SLUG }}")
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Preview URL: $URL"

      - name: Wait for preview to be ready
        run: |
          for i in {1..10}; do
            if curl -sSfL "${{ steps.vercel.outputs.url }}" > /dev/null; then
              echo "Preview is ready."
              exit 0
            fi
            echo "Waiting preview... ($i/10)"
            sleep 3
          done
          echo "Preview did not become ready in time." >&2
          exit 1

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E on Preview
        env:
          BASE_URL: ${{ steps.vercel.outputs.url }}
        run: npm run e2e --if-present
