name: Frontend CI
on:
  push: { branches: [ main ] }
  pull_request:
    branches: [ main ]
    paths:
      - "**"
      - ".github/workflows/frontend-ci.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Typecheck
        run: npm run typecheck --if-present
      - name: Unit tests (Vitest)
        run: npm run test:coverage --if-present
      - name: Build
        run: npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
