name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "score-manager-frontend/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: score-manager-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # ← cache 設定は一旦オフにします

      # 手動キャッシュ（最も安定）
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('score-manager-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Debug show files
        run: |
          pwd
          ls -la
          ls -la ../score-manager-frontend

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Unit tests (Vitest)
        run: npm run test:coverage --if-present

      - name: Build
        run: npm run build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: score-manager-frontend/dist
