name: Frontend Preview & E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "score-manager-frontend/**"
      - ".github/workflows/frontend-preview-e2e.yml"

jobs:
  preview-and-e2e:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    defaults:
      run:
        working-directory: score-manager-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "score-manager-frontend/package-lock.json"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel (Preview)
        id: vercel
        run: |
          URL=$(npx vercel deploy --prebuilt --yes \
            --token "$VERCEL_TOKEN" \
            --scope "$VERCEL_ORG_ID")
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Preview URL: $URL"

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E on Preview
        env:
          BASE_URL: ${{ steps.vercel.outputs.url }}
        run: npm run e2e --if-present
