name: Frontend Preview & E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "**"  # リポジトリ直下がフロントのため全体でOK。必要なら絞ってもOK
      - ".github/workflows/frontend-preview-e2e.yml"

jobs:
  preview-and-e2e:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      # 事前ビルドして prebuilt デプロイを高速化（Vite想定）
      - name: Build
        run: npm run build

      - name: Add Vercel CLI
        run: npm i -D vercel

      - name: Deploy to Vercel (Preview)
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel pull --yes --environment=preview --token "$VERCEL_TOKEN"
          # dist をそのままアップ（--prebuilt）
          URL=$(npx vercel deploy --prebuilt --yes --token "$VERCEL_TOKEN")
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Preview URL: $URL"

      # プレビューURLが応答可能になるまで軽く待つ（最大 ~30秒）
      - name: Wait for preview to be ready
        run: |
          for i in {1..10}; do
            if curl -sSfL "${{ steps.vercel.outputs.url }}" > /dev/null; then
              echo "Preview is ready."
              exit 0
            fi
            echo "Waiting preview... ($i/10)"
            sleep 3
          done
          echo "Preview did not become ready in time." >&2
          exit 1

      # E2E（Playwright想定。Cypress の場合は置き換え）
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E on Preview
        env:
          BASE_URL: ${{ steps.vercel.outputs.url }}
        run: npm run e2e --if-present
